importing Numpy Library

In [56]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have same shape

In [57]:
# creating two matrices

A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [58]:
print(A)

[[2 3]
 [4 5]]


In [59]:
print(B)

[[6 7]
 [8 9]]


In [60]:
A.shape

(2, 2)

In [61]:
B.shape

(2, 2)

Adding two Matrices

In [62]:
sum = A + B

In [63]:
print(sum)

[[ 8 10]
 [12 14]]


In [64]:
# create two matrices with random values

matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(20, size=(3, 3))

In [65]:
print(matrix_1)

[[2 8 5]
 [9 0 0]
 [5 4 0]]


In [66]:
print(matrix_2)

[[11 17  0]
 [19 14  6]
 [19  5 17]]


In [67]:
sum = np.add(matrix_1, matrix_2)

In [68]:
print(sum)

[[13 25  5]
 [28 14  6]
 [24  9 17]]


In [69]:
# create two matrices with random values

matrix_3 = np.random.randint(10, size=(3, 3))
matrix_4 = np.random.randint(20, size=(3, 4))

In [70]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

we get this error because matrix_3 and matrix_4 have different shapes

Matris Subtraction

In [79]:
# creating two matrices

A = np.array([[2, 3], [4, 5]])

B = np.array([[6, 7], [8, 9]])

In [80]:
print(A)

[[2 3]
 [4 5]]


In [81]:
print(B)

[[6 7]
 [8 9]]


In [82]:
difference = A - B

In [83]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [84]:
# create two matrices with randon values
matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(20, size=(3, 3))

In [85]:
print(matrix_1)

[[6 8 1]
 [4 8 7]
 [8 2 8]]


In [86]:
print(matrix_2)

[[10  0  6]
 [ 8 13 10]
 [17  9 16]]


In [71]:
diff = np.subtract(matrix_1, matrix_2)

In [72]:
print(diff)

[[ -9  -9   5]
 [-10 -14  -6]
 [-14  -1 -17]]


**Multing a matrix by a scalar**

In [73]:
x = 5
y = np.random.randint(10, size=(4, 4))

In [74]:
print(y)

[[2 7 6 4]
 [7 3 8 5]
 [4 9 7 0]
 [0 2 4 7]]


In [75]:
product = np.multiply(x, y)

In [76]:
print(product)

[[10 35 30 20]
 [35 15 40 25]
 [20 45 35  0]
 [ 0 10 20 35]]


Multplying 2 Matrices

In [90]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(20, size=(4, 4))

In [88]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [89]:
product = np.dot(matrix_3, matrix_4)

**Element wise Matrix Multpication **

In [109]:
# create two matrices with random values
matrixs_3 = np.random.randint(10, size=(3, 3))
matrixs_4 = np.random.randint(20, size=(3, 3))

In [95]:
print(matrix_3)

[[8 1 6]
 [3 1 2]
 [0 9 6]]


In [96]:
print(matrix_4)

[[ 0  1  1 11]
 [18 16 14 17]
 [ 0  2  7 12]]


In [110]:
product = np.multiply(matrixs_3, matrixs_4)

In [98]:
print(product)

[[ 18  36  64 177]
 [ 18  23  31  74]
 [162 156 168 225]]


In [112]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3, 3))
matrix_2 = np.random.randint(20, size=(4, 3))

In [113]:
product = np.multiply(matrix_3, matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 