In [1]:
import numpy as np

Creating a Matrix using nimpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [11]:
martrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(martrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [12]:
martrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [14]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.24557269 0.1482002  0.82083519]
 [0.64000492 0.11948127 0.80550589]
 [0.80912921 0.9752066  0.34207794]]


In [19]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size = (4,5))
print(random_integer_matrix)

[[57 62 17 84 79]
 [ 8 93 74 16 45]
 [92 47 26 90  3]
 [47 48 27 82 76]]


Matrix with all the values as 1

In [22]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or zero Matrix

In [24]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [25]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [27]:
a = np.random.randint(100, size = (4,5))
print(a)

[[39 72 84 48 78]
 [53 16 97  8 58]
 [ 2 42 29 86 27]
 [38 81 95 85 32]]


In [28]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[39 53  2 38]
 [72 16 42 81]
 [84 97 29 95]
 [48  8 86 85]
 [78 58 27 32]]
